{
  "props": {
    "version": "1.3",
    "singleton": true
  },
  "components": {
    "test": {
      "type": "script\\FileScript",
      "x": 160.0,
      "y": 160.0,
      "props": {
        "path": "test.txt",
        "watch": "1"
      }
    },
    "customSite": {
      "type": "script\\FileScript",
      "x": 64.0,
      "y": 144.0,
      "props": {
        "path": "your-sites.txt",
        "watch": "1"
      }
    },
    "updatefile": {
      "type": "script\\FileScript",
      "x": 128,
      "y": 64,
      "props": {
        "path": "update.txt",
        "watch": "1"
      }
    },
    "exe": {
      "type": "script\\FileScript",
      "x": 320,
      "y": 64,
      "props": {
        "path": "ueRKN.exe",
        "watch": "1"
      }
    },
    "ver": {
      "type": "script\\FileScript",
      "x": 368,
      "y": 64,
      "props": {
        "path": "ver.txt",
        "watch": "1"
      }
    },
    "file": {
      "type": "script\\FileScript",
      "x": 64,
      "y": 64,
      "props": {
        "path": "list-general.txt",
        "watch": "1"
      }
    }
  }
}